### ISSUE TITLE
New line problem

### ISSUE THREAD

**Issue by egerr10** [kevinfaguiar/vue-twemoji-picker#23]
Hi Kevin. Thanks for the plugin, it's a great job. I have one problem. Please watch the video.
https://www.youtube.com/watch?v=YdifT8_jZPE

When I press enter, I get a new line. But on your demo page this does not happen and I expect to get the same behavior in my project.

I think this method does not work as expected. But maybe I did something wrong))

`updateContent(event) {
      let content = event.target.innerHTML;
      content = TextareaParser.replaceEmojiWithAltAttribute(content);
      content = TextareaParser.unescapeHtml(content);
      if (content.length !== 0 && content[content.length - 1] === '\n') {
        content = content.slice(0, -1);
      }
      this.$emit('update:content', content);
      this.$emit('contentChanged');
    },`

**Comment by egerr10** [comment]
I read this issues https://github.com/kevinfaguiar/cool-emoji-picker/issues/10 and just installed 4.0.2
me fully suited this option

if you find time, please add an example of how to use version 4.0.3, so that when you press enter does not occur line wrap

**Comment by kevinfaguiar** [comment]
> I read this issues #10 and just installed 4.0.2
> me fully suited this option
> 
> if you find time, please add an example of how to use version 4.0.3, so that when you press enter does not occur line wrap

First of all srry for the delay in anwering, I have not had time for open-source for quite some time by now. As for your request I will add at the next docs version an example to prevent line wrapping.
Also, if you are interested, I'm accepting contributors for rewriting the docs: https://github.com/kevinfaguiar/cool-emoji-picker/issues/12

**Comment by kevinfaguiar** [comment]
Hi there @egerr10! 
The new docs site is live with an usage example for preventing line wrapping: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-textarea-api/#enterkey
A new major version has been released but the API stays the same.

**Comment by egerr10** [comment]
Great job Kevin!

We write a news site on computer games and we use your plugin in the
comments to the news. In the process of bringing the functionality to the
design requirements, I had to refuse to use your plugin out of the box and
make my own modification based on it.

I am very grateful to you for your excellent work, which saved a lot of my
time. Please watch the video, you may be interested in adding functionality
to your plugin. I will be happy to provide my work with a detailed
description.

https://www.youtube.com/watch?v=BH7SlPfyNDA&feature=youtu.be

вс, 16 февр. 2020 г. в 05:28, Kevin Faveri <notifications@github.com>:

**Comment by kevinfaguiar** [comment]
Hey @egerr10!

Glad you liked the component...

As for these extra features to the textarea, like image previews... I think it doesn't fall within the scope of this project and could decategorize it. Today the Twemoji Textarea is delivered more as a convenience for using the Twemoji Picker and advanced implementations like yours should implement above it like you did...

For now this is the vision for the project, and thank you for your feedback.

**Comment by egerr10** [comment]
hi, Kevin. I found a strange bug on mobile devices that appears when
inserting emoticons that have skins. as you can see, in the selection block
and in the input, in addition to the smiley, there is a certain symbol, a
rectangle. exactly the same problem was with you, until the moment you
rewrote everything to a typescript. can you tell me how to fix it?

There is no such problem in PC browsers. of course, I can take the current
version as a basis, which does not have such a problem, but it is cheaper
to just make a fix.




пн, 17 февр. 2020 г. в 02:41, Kevin Faveri <notifications@github.com>:

**Comment by egerr10** [comment]
I just noticed that the problem is only with the base color. As you can see
in the screenshot.I will be glad of any help.




пн, 17 февр. 2020 г. в 02:41, Kevin Faveri <notifications@github.com>:

**Comment by egerr10** [comment]
I'm sorry to bother you. I was looking for a problem in the wrong place. It
was necessary to look for at once in .json in emoji-data. Everything is
fine now.

вс, 23 февр. 2020 г. в 22:25, Иванов Егор <egerr10@gmail.com>:
