### ISSUE TITLE
Placeholder in textarea

### ISSUE THREAD

**Issue by byinff** [kevinfaguiar/vue-twemoji-picker#32]
Hi, does the plugin support textarea placeholder ?

**Comment by kevinfaguiar** [comment]
Hi there! 
Currently it does not support a placeholder since it is a [contenteditable] div behind, but such feature is possible to implement. I will look into it.

**Comment by byinff** [comment]
Thanks for you reply. I will waiting for this implementation

**Comment by byinff** [comment]
Hi, it can be useful https://stackoverflow.com/questions/20726174/placeholder-for-contenteditable-div

**Comment by kevinfaguiar** [comment]
Yeah!! I'm planning in developing something like that

**Comment by kevinfaguiar** [comment]
Hi there @byinff 
This has been implemented in v5.2.3: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-textarea-api/#placeholder
