### ISSUE TITLE
The popper is too far away from the popper trigger

### ISSUE THREAD

**Issue by guanzo** [kevinfaguiar/vue-twemoji-picker#51]
I set `pickerArrowEnabled` to false, which makes the arrow go away, but the popper doesn't change position, leading to a big gap between the popper and the trigger. It looks weird.

Even with the arrow, the popper is too far away imo. With or without the arrow, the popper should be within 5-10px. My trigger is exactly 24px by 24px, there is no extra, invisible spacing due to padding or w/e.

With arrow: 

![witharrow](https://i.gyazo.com/9956c9944740eda059e0bba8fe75da57.png)
Without arrow:

![noarrow](https://i.gyazo.com/cb9c4cc0f82837df021a549152294e41.png)

**Comment by kevinfaguiar** [comment]
Could you provide a codesandbox or codepen for this scenario? Thank you for the feedback Eric!

**Comment by guanzo** [comment]
https://codesandbox.io/s/festive-goodall-zxymf

You can toggle `pickerArrowEnabled` to see the difference.

In both cases, the popper is too far away for my taste.

**Comment by kevinfaguiar** [comment]
Hi there @guanzo!

I've done some tweaking in the TwemojiPicker positioning for a lot of use cases, and it should better fit your needs now. The tweak is available from version: 5.6.1 onwards.
