### ISSUE TITLE
How to programmatically close the popper?

### ISSUE THREAD

**Issue by guanzo** [kevinfaguiar/vue-twemoji-picker#52]
passing `true` to `emojiPickerDisabled` just seems to make the popper unclickable. Toggling `this.$refs.picker.isPickerOpen = false` doesn't work either, where `this.$refs.picker` refers to `<TwemojiPicker>`.

I like this lib a lot, the way it looks visually I mean. But it doesn't seem particularly reactive to changes in data/props.

EDIT: Going to go with another lib for now. Good luck with this one.

**Comment by kevinfaguiar** [comment]
Hi there Eric! 
Just saw the issues you have opened...
Anyway, thank you so much for the for valuable feedback. 
I will be addressing each issue particularly when I have time.

**Comment by kevinfaguiar** [comment]
Starting from version 5.5.5 onwards changing the `this.$refs.picker.isPickerOpen` value will trigger the expected reactivity... so for now this can be used for opening and closing the picker programatically.
Also, setting emojiPickerDisabled to true and not closing the popper seems to be counterintuitive... So now, if emojiPickerDisabled is set to true and the picker is opened, it will be closed.
