### ISSUE TITLE
Can't set content property initially in TwemojiTextarea.

### ISSUE THREAD

**Issue by k18923** [kevinfaguiar/vue-twemoji-picker#55]
https://github.com/kevinfaguiar/vue-twemoji-picker/blob/7094fb244e94a844b9b24fb1b42b1b6fb173e71d/src/components/TwemojiTextarea.vue#L203-L210

It might be below?
``` javascript
if (this.content.length) {
     twemojiTextarea.innerHTML = this.content; 
} 
```

**Comment by COil** [comment]
Hi @k18923 , you want to add some content in the textarea as soon as the component appears?  🤔

**Comment by k18923** [comment]
Hi, @COil . Thanks for your comment.

I what to set content initial value when the twemoji-textarea component mounted, not placeholder.

I tried `addText` function, but the function get auto focus to the component (I guess that `HTMLElement.focus()` is called internally)... 

So, I set initial value directly from parent component.
``` javascript
mounted() {
  this.$refs.textarea.$refs.twemojiTextarea.innerHTML = this.video.comment;
}
```

**Comment by kevinfaguiar** [comment]
Hi there @k18923!

I've just updated and added a new prop to TwemojiTextarea: 'initialContent'. It will set the initial content of the textarea on component mount, almost like you did on a parent component.

You can use the prop like that:
```Vue
<twemoji-textarea
        :emojiData="emojiDataAll"
        :emojiGroups="emojiGroups"
        initialContent="INITIAL CONTENT HERE"
      >
      </twemoji-textarea>
```

I've also updated the docs: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-textarea-api/#initialcontent

---

Also, if you need to addContent to the textarea programatically the current solution is using something like that (using Vue ref):
```javascript
this.$refs.twemojiTextareaRef.addText('toto');
```

Or manually, like that (which will be the way when developing advanced features on the parent component):

```javascript
const innerHtml = this.$refs.textarea.$refs.twemojiTextarea.innerHTML;
const modifiedInnerHtml = innerHtml + 'NEW TEXT ADDED';
this.$refs.textarea.$refs.twemojiTextarea.innerHTML = modifiedInnerHtml;
