### ISSUE TITLE
Problem with the pickerWidth prop

### ISSUE THREAD

**Issue by COil** [kevinfaguiar/vue-twemoji-picker#58]
Hi,

I am trying to set the "pickerWidth" prop. 

1) If I don't set it, I have the default size => OK

2) If I put the id of the parent element of the input, I don't have errors, but the picker is broken. I guess it can come from my CSS. => OK

3) If I put a fake value like "auto" 

`:pickerWidth="'auto'"`

I have the following warning:

`The value you entered is invalid: should be a number or a ID tag beginning with "#"`

But this time, the picker is correctly displayed and takes the width of its parent! That's weird. How to have this behavior without having this warning in the console?

**Comment by kevinfaguiar** [comment]
Hi there COil! Please share a codesandbox with the scenario so I can better explore the code.

**Comment by COil** [comment]
Here is a demo: https://myemojis.best/?uuid=e8412601-0b04-4ba8-b26e-f37874b49a2f

**Comment by kevinfaguiar** [comment]
This is not showing any warning the console... Would be good for debugging purposes if you sent a Codesandbox with the two scenarios you wish to be solved since I could not reproduce it locally :(

**Comment by COil** [comment]
Hi, hum indeed I guess the error only show in my local development environment. 

But, what can't you reproduce? You don't have an error when putting `:pickerWidth="'auto'"` in your code?

I can't create a sandbox with my whole application. 

For me, the bug is that you don't have the same behaviour when not putting this prop and when putting a "wrong" value like `auto`. As it is considered as an error, it should fall back to the default value.

**Comment by kevinfaguiar** [comment]
Hmm.. Maybe I can solve it by:

-  When it is an invalid value, use the default (I think it is not behaving like that right now) but still shows a warning

I think it would be interesting if you could debug your scenario two, since I could not reproduce it here:
```
If I put the id of the parent element of the input, I don't have errors, but the picker is broken. I guess it can come from my CSS. => OK
```

Because it could be a CSS bug in the component, in fact. If you do, please open another issue with a codesandbox so I can debug too :)

**Comment by kevinfaguiar** [comment]
Hi there Coil! As you can see here, from version 5.6.4 onwards, it will use the default value if it cant identify the prop: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-picker-api/#pickerwidth

**Comment by COil** [comment]
Ok, let me try with the new release to see if it fixes the problem.

**Comment by COil** [comment]
Hi Kevin,

I have tested your fix for the picker width check; it's OK.

To fix my specific problem I had to add the following CSS, so the picker takes the parent width :

```
#emoji-popup {
    width: revert !important;
}

.emoji-popover-inner {
    width: revert !important;
}
```

Maybe, it should be mentioned in the doc? Or an 'auto' or 'parent' value could be added?
It would be easier than fixing it through CSS.

**Comment by kevinfaguiar** [comment]
I think that having the picker predict all use cases in style isnt a good approach... But the picker should be taking the parent width if you pass to the prop the element ID starting with '#'. If not, then it is a bug.
Would love to see a codesandbox for reproducing this bug.

**Comment by COil** [comment]
You are right. How can I debug locally?

**Comment by kevinfaguiar** [comment]
I can't reproduce the bug either in the published versions or in dev environment so I would need to see your code through having a codesandbox would help a lot for solving your problem.

Also, if you want to do this yourself, I would suggest debugging the styles and the pickerWidth prop so you can figure why it isnt behaving accordingly.

**Comment by COil** [comment]
Hi Kevin, I made a new try. 

It's Ok now if I put the main Vue.js container `:pickerWidth="'#app'"` which encapsulates everything. I can now delete the additional CSS rules with the revert statements for the width.
Does that make sense to you?  See you.  🙂
