### ISSUE TITLE
Change props Twemoji Picker of in Twemoji Textarea

### ISSUE THREAD

**Issue by jiligel803** [kevinfaguiar/vue-twemoji-picker#61]
What is the right way to customize Twemoji Picker when call Twemoji Textarea.
It's available only with default props.

**Comment by jiligel803** [comment]
I mean how to call `<template v-slot:twemoji-picker-button>` inside Twemoji Textarea

**Comment by kevinfaguiar** [comment]
Hi there @jiligel803! It is currently not implemented in textarea but I will mark this issue for developing this feature!

**Comment by kevinfaguiar** [comment]
Starting from version 5.7.2 onwards the TwemojiTextarea will support the picker slots: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-textarea-api/#slots
