### ISSUE TITLE
Twemoji picker crashes in IE 11

### ISSUE THREAD

**Issue by jiligel803** [kevinfaguiar/vue-twemoji-picker#65]
IE 11 `vue-twemoji-picker` Doesn't work in IE. 
Error with obejct and method "assign"

**Comment by kevinfaguiar** [comment]
HI there! Check Requirements here: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/#requirements
Try integrating polyfills into your app or use polyfill.io for ensuring compatibility.
