### ISSUE TITLE
<twemoji-picker> - did you register the component correctly?

### ISSUE THREAD

**Issue by DaviMenezes** [kevinfaguiar/vue-twemoji-picker#69]
Unknown custom element: <twemoji-picker> - did you register the component correctly?
![image](https://user-images.githubusercontent.com/3998868/84954802-7ae70980-b0cc-11ea-9eb7-4b0e7872d7cb.png)

**Comment by kevinfaguiar** [comment]
Hi there!

Current master branch (NPM latest) is working as expected (the docs use it).

This must be happening only on your code setup, unfortunately. 

If it persistis please create a Codesandbox with your code so I can reproduce.

**Comment by kevinfaguiar** [comment]
Closing as
