### ISSUE TITLE
How to render picker emoji in textbox

### ISSUE THREAD

**Issue by beshoo** [kevinfaguiar/vue-twemoji-picker#73]
As we know that picker return the utf code.
But it does not render the emoji to images... 

How can we address this issue? 

Regard

**Comment by kevinfaguiar-tc** [comment]
The picker return the img tag and the unicode: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-picker-api/#events

For rendering you have two choices: use the provided Textarea or create your own textarea.

**Comment by kevinfaguiar** [comment]
The picker return the img tag and the unicode: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-picker-api/#events

For rendering you have two choices: use the provided Textarea or create your own textarea.

**Comment by beshoo** [comment]
> The picker return the img tag and the Unicode: https://kevinfaguiar.github.io/vue-twemoji-picker/docs/twemoji-picker-api/#events
> 
> For rendering you have two choices: use the provided Textarea or create your own textarea.

Thank you so much but if I want to create my own contenteditable div as a textarea, please can you advise me if I pick an emoji form the picker how to place the emoji image or the Unicode in the place where the course was located! since the user will leave the contenteditable and click on the picker to choose from! what if he locates the course in the middle of a word!

Thank you
