### ISSUE TITLE
Please can you provide an example with Picker and textaria which can be an inputbox! in sizse!

### ISSUE THREAD

**Issue by beshoo** [kevinfaguiar/vue-twemoji-picker#74]
It will be nice if you please provide an example of how to use the picker with the Textarea
I know that you are using "**contenteditable**"!

I don't want to use the expanded picker, but the normal picker which can be placed anywhere around the textarea ! maybe at the corner of the text area as a small smile!

sometime we may need the size of the text area to be as small as input box, the expanded animation will not fit this way. 
but the small piker will be great.

As long as you are the author of this wonderful plugin, I hope that you may be kind enough to provide an example! 

regards

**Comment by kevinfaguiar** [comment]
Guy, please, stop spamming. 

Developing an integration between this plugin and an HTML Input or Textarea is not on the scope of this project as I imagine. 

However, the project is open-source, so you are free to fork it or make a Pull Request with this feat.
